#!/bin/bash

CWDMD5=`echo pwd | md5sum | cut -f1 -d" "`

if [ ! -d "/home/vagrant/.workspace_npm_cache/$CWDMD5" ]; then
    echo "--> Creating cache ID: $CWDMD5"
    mkdir -p /home/vagrant/.workspace_npm_cache/$CWDMD5    
fi

if [ ! -L "$PWD/node_modules" ]; then    

    if [ -d "$PWD/node_modules" ]; then
        echo "--> Removing original node_modules directory ..."
        rm -rf $PWD/node_modules
    fi

    echo "--> Updating NPM symlink"
    ln -s $PWD/node_modules /home/vagrant/.workspace_npm_cache/$CWDMD5
fi

docker run --rm --interactive --tty --volume $PWD:/usr/src/app -w /usr/src/app node npm "$@"